### ISSUE TITLE
Use signac >2

### ISSUE THREAD

**Issue by cbkerr** [mosdef-hub/CECAM-MoSDeF-Workshop#7]
I noticed that signac is pinned at 1.7.0 in [environment.yml](https://github.com/mosdef-hub/CECAM-MoSDeF-Workshop/blob/main/environment.yml).

To make the syntax uniform between your tutorial and the signac one, please develop/test the tutorial on the latest versions!

Let me know if you need help upgrading your scripts.

I looked through the results from [searching "signac" on the entire mosdef-hub organization](https://github.com/search?q=org%3Amosdef-hub+signac&type=code), and I think the only thing that will cause breakage is the deprecation of project ids in a few old tutorials. Use subdirectories instead.

**Comment by CalCraven** [comment]
We actually are installing signac=2.0 since the notebooks are hosted on Colab, which is getting the latest version from conda-forge instead of from the yml, which is why that wasn't being caught. I opened a PR to fix the yml as well.

The Signac bits are in the solvated_surface_workflow/Solvated_Surface.ipynb, if you want to have a look.
